version: '3.8'
services:
  sheet:
    image: openjdk:11
    container_name: sheet_service
    volumes:
      - ./src:/src
    working_dir: /src
    command: >
      bash -c "mkdir -p /classes && 
              javac -d /classes Main.java && 
              java -cp /classes Main"