version: '3.8'
services:
  sheet:
    image: openjdk:8
    container_name: sheet_service
    volumes:
      - ./src:/src
      - ./activate.sh:/activate.sh
    command: >
      bash -c "chmod +x activate.sh && 
              ./activate.sh"