version: '3.8'
services:
  sheet:
    image: openjdk:8
    container_name: sheet_service
    volumes:
      - ./src:/src
    command: >
      bash -c "mkdir -p ./classes
              javac -d ./classes ./src/*.java
              java -cp ./classes Main"